### ISSUE TITLE
When you get a new account on any other platform send it here not at my repositories 

### ISSUE THREAD

**Issue by suegdu** [TranCongVinh/web#1]

**Comment by TranCongVinh** [comment]
Oof ,-,

**Comment by suegdu** [comment]
did you get any account?

**Comment by TranCongVinh** [comment]
;-; no, i choose give them proof, just  wait i will get a new student card soon

**Comment by suegdu** [comment]
bruh

**Comment by suegdu** [comment]
they will not check if it is    just make a new account on any other platform

**Comment by suegdu** [comment]
just create any new account

**Comment by TranCongVinh** [comment]
> just create any new account

Bot lost ;-; server gone

**Comment by suegdu** [comment]
create a new account

**Comment by suegdu** [comment]
create a new account

**Comment by suegdu** [comment]
create a new account

**Comment by TranCongVinh** [comment]
;-; "spem" god
i know ;-; i will use my old account
can u give me my server invite link pls ;-;

**Comment by suegdu** [comment]
which server?

**Comment by TranCongVinh** [comment]
> which server?

TCV white pfp ;-;

**Comment by suegdu** [comment]
i left the server while ago

**Comment by suegdu** [comment]
is that bc of your bitcoin?

**Comment by suegdu** [comment]
couldnt you get the client id ?

**Comment by TranCongVinh** [comment]
;-;

**Comment by suegdu** [comment]
bruh

**Comment by suegdu** [comment]
i need to talk but not here also how do you asking me for an invite link for the server while you dont have an account

**Comment by TranCongVinh** [comment]
;-; 7 discord alts already

**Comment by suegdu** [comment]
TranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterdayTranCongVinh commented yesterday

**Comment by TranCongVinh** [comment]
;-; i have test

**Comment by TranCongVinh** [comment]
send me your name and tag

**Comment by TranCongVinh** [comment]
no

**Comment by TranCongVinh** [comment]
;-; send me friend rq
TCV alt#2106

**Comment by suegdu** [comment]
alr

**Comment by suegdu** [comment]
bruh i just noticed that i sent a request for the wrong person i thought its just "alt#2106"
